version: "3.9"
services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
  phpunit:
    image: php:8.1-apache
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
volumes:
  app:
  dbData:
